/* TODO: ADD BRIEF AND SPLIT THE CODE IN INCLUDES, GLOBAL VARIABLES, GLOBAL FUNCTIONS, LOCAL FUNCTIONS SECTIONS */

#ifndef DISPLAY_H
#define DISPLAY_H

#include <stdbool.h>

bool display_init(void);

#endif /* DISPLAY_H */
